Console.Write("Введите число в милиметрах: ");
double milimeter = double.Parse(Console.ReadLine());
const double sm = 10;
const double m = 1000;
const double km = 100000;
const double mil = 1609344;
const double yard = 914.4;
Console.WriteLine($"В {milimeter}милиметров {milimeter/sm:F2}сантиметров");
Console.WriteLine($"В {milimeter} милиметров {milimeter/m:F2} метров");
Console.WriteLine($"В {milimeter} милиметров {milimeter / km:F2} километров");
Console.WriteLine($"В {milimeter} милиметров {milimeter / mil:F2} миль");
Console.WriteLine($"В {milimeter} милиметров {milimeter / yard:F2} ярд");